// <auto-generated />
using System;
using DBOperationWithEFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DBOperationWithEFCore.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260115123646_updatedLanguages")]
    partial class updatedLanguages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DBOperationWithEFCore.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfpages")
                        .HasColumnType("int");

                    b.Property<int>("languageId")
                        .HasColumnType("int");

                    b.Property<string>("tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("languageId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("DBOperationWithEFCore.Data.BookPrices", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CurrenciesId")
                        .HasColumnType("int");

                    b.Property<int>("bookid")
                        .HasColumnType("int");

                    b.Property<int>("currencyid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CurrenciesId");

                    b.HasIndex("bookid");

                    b.ToTable("bookPrices");
                });

            modelBuilder.Entity("DBOperationWithEFCore.Data.Currencies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "INdia",
                            tittle = "INR"
                        },
                        new
                        {
                            Id = 2,
                            Description = "USA",
                            tittle = "Doller"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Europe",
                            tittle = "Euro"
                        },
                        new
                        {
                            Id = 4,
                            Description = "jsfhjdjf",
                            tittle = "Dinar"
                        });
                });

            modelBuilder.Entity("DBOperationWithEFCore.Data.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tittle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "INdia",
                            tittle = "Hindi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "English",
                            tittle = "English"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Urdu",
                            tittle = "Urdu"
                        },
                        new
                        {
                            Id = 4,
                            Description = "panjabi",
                            tittle = "panjabi"
                        });
                });

            modelBuilder.Entity("DBOperationWithEFCore.Data.Book", b =>
                {
                    b.HasOne("DBOperationWithEFCore.Data.Language", "Languages")
                        .WithMany("Books")
                        .HasForeignKey("languageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Languages");
                });

            modelBuilder.Entity("DBOperationWithEFCore.Data.BookPrices", b =>
                {
                    b.HasOne("DBOperationWithEFCore.Data.Currencies", "Currencies")
                        .WithMany()
                        .HasForeignKey("CurrenciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBOperationWithEFCore.Data.Book", "Books")
                        .WithMany()
                        .HasForeignKey("bookid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");

                    b.Navigation("Currencies");
                });

            modelBuilder.Entity("DBOperationWithEFCore.Data.Language", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
